# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeiOSExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativeiOSExample
  pod 'TesseractOCRiOS', :git => 'https://github.com/chaoskyme/Tesseract-OCR-iOS.git'

end
